### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by speedboattoyota** [evolutionsoftswiss/pokernow-handhistory-converter#18]
I'm running this on windows but getting the following code errors. Would you be able to look into it? I've linked an example log file.

[log_120422.csv](https://github.com/evolutionsoftswiss/pokernow-handhistory-converter/files/10292516/log_120422.csv)

        Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -19
        at java.lang.String.substring(U

        at ch.evolutionsoft.poker.pokernow.PokernowSingleHandConverter.readHandNumber(PokernowSingleHandConverter.java:382)
        at ch.evolutionsoft.poker.pokernow.PokernowHandHistoryConverter.convertHandHistory(PokernowHandHistoryConverter.java:300)
        at ch.evolutionsoft.poker.pokernow.PokernowHandHistoryConverter.main(PokernowHandHistoryConverter.java:92)

**Comment by evolutionsoftswiss** [comment]
Thanks for posting this issue.

I was able to reproduce it with pokernow logs of the old format.
I'll improve the behavior to support older formats later.

In the meantime you could try to move away older logs to be able to process all newly formatted logs.

**Comment by speedboattoyota** [comment]
Thanks what did you mean by older logs? I have been downloading them the same way each time. Is there another way to download the logs in a newer format?

**Comment by evolutionsoftswiss** [comment]
I mean older logs not containing the id part in the lines with the hand number. Even if you download the full log always the same way, the log format had a change, around a month ago, maybe to support the instant replays.

- new log line "-- starting hand #136 (id: x6bgj4s2hsjw)  (No Limit Texas Hold'em) (dead button) --"
- old log line "-- starting hand #136 (No Limit Texas Hold'em) (dead button) --"

Now these old log lines below are causing the error you've observed.

The error is not coming from the new file you've attached, but from an older file in the same directory.

**Comment by evolutionsoftswiss** [comment]
Could you please try if the new version [Release v0.2.5](https://github.com/evolutionsoftswiss/pokernow-handhistory-converter/releases/tag/v0.2.5) corrects your error message ?

**Comment by speedboattoyota** [comment]
Thanks it worked. Appreciate the quick fix.
