### ISSUE TITLE
Counts straddles as VPIP

### ISSUE THREAD

**Issue by spoder22** [evolutionsoftswiss/pokernow-handhistory-converter#20]
It seems PT4 counts straddles as VPIPs, since straddles are not possible in PokerStars hand histories.

Would it be possible to change the hand history output file to a different site where straddles are possible? I believe GGPoker has this capability.

**Comment by evolutionsoftswiss** [comment]
Thanks for this important observation. PokerStars format was chosen initially because of the available hand history examples.
It would be possible to change the output format to a different site, but that's definitely something that would take a longer time to complete.

**Comment by evolutionsoftswiss** [comment]
Are you sure straddles should not count to VPIP, have you got a source for that ?

Beside antes, small blind and big blind, it could get interpreted as "voluntary put in pot" and thus the current straddle handling with VPIP would be correct.

**Comment by spoder22** [comment]
Technically you can choose whether or not to straddle, which means that it is voluntary. But some games have a mandatory straddle, which cannot be distinguished from a voluntary straddle.
