### ISSUE TITLE
Hmmm... not sure if these are issues.

### ISSUE THREAD

**Issue by Deckhole** [evolutionsoftswiss/pokernow-handhistory-converter#6]
I am new to Github, and do not know how to leave general comments and questions.  I do a bit of Java programming and would love to contribute to this project (PokerNowConverter).

I also have some initial questions:
1) Does running-it-twice work?
2) Live Straddles work?

How can I contribute to the code?  I would like to add a feature that interrogates the file enough to know that the blinds are increasing and thus designates that the game is a tournament instead of a cash game for PokerTracker and HoldemManager.

Thanks!
Mark

**Comment by evolutionsoftswiss** [comment]
Close this Issue. Issues may be currently the only way to comment.

Discussions are not activated yet.
