### ISSUE TITLE
Antes are causing Errors

### ISSUE THREAD

**Issue by Deckhole** [evolutionsoftswiss/pokernow-handhistory-converter#8]
When Antes are introduced, hands are not converting.
[ErrorHands-20211010010523.txt](https://github.com/evolutionsoftswiss/pokernow-handhistory-converter/files/7319600/ErrorHands-20211010010523.txt)

**Comment by evolutionsoftswiss** [comment]
I'll look into this and will try to support antes in an upcoming version.

**Comment by evolutionsoftswiss** [comment]
Could you provide an original csv with at least one complete hand where antes were used ?

**Comment by Deckhole** [comment]
Certainly!   Here is a file attachedd.

Also, if I am going to work on code enhancements, I will need a significant source of hand histories generated by PokerStars.   As a U.S. person, I am working in the dark, because I do not have access to PokerStar's handhistory examples to know how I need to format them.

Is there anyway there could be a .zip file with a good variety of PokerStars handhistories?   OR is there a resource that goes through how PokerStars documents hands
[poker_now_log_DZ2aUZbTnUIjRWRgb0c53x0l_.csv](https://github.com/evolutionsoftswiss/pokernow-handhistory-converter/files/7360782/poker_now_log_DZ2aUZbTnUIjRWRgb0c53x0l_.csv)
?

**Comment by Deckhole** [comment]
Certainly!  Thanks for working on this.

I attached a file.   I also updated on GitHub.

Do you happen to know of a resource that either describes how PokerStars
formats their HandHistory or a place where I can have access to all the
various types of hands and situations in PokerStars and how it is
documented in their HandHistory?

I am a US citizen and do not have access to PokerStars HandHistory, so I do
not know all the syntax that is used to document all the various
situations.   I nice reservoir of examples OR a document resource that
describes the syntax would be very helpful in my being able to contribute
to the Handconverter Code.

Thanks!
Mark
