### ISSUE TITLE
"Hero" hole-cards not present in conversion

### ISSUE THREAD

**Issue by Deckhole** [evolutionsoftswiss/pokernow-handhistory-converter#9]
When selecting readYourHoleCards = true, the converter adds a "Hero shows [ HCs1 HCs2 ]" at the end of the hand, as if the "Hero" decided to expose their cards to everyone.

However, this method of indicating hole-cards does not allow many HandHistory trackers the ability to determine who the "Hero", nor does it allow for the reader to track whether or not the "Hero" actually exposed their hole-cards.

Possibly this could be considered a suggestion, rather than an issue, however, because HoldemManager actually mis-interprets who the Hero is and whether or not cards were actually exposed, I am considering it an issue.

Thanks again,
Mark

**Comment by evolutionsoftswiss** [comment]
That's a valuable observation. For me it was enough to see all my hole cards in the hands overview. The improvement to distinguish that information from a "show hand to all" will go into an upcoming new version.
